/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.view;

import app.controller.MenuPrincipalController;

/**
 *
 * @author vinic
 */
public class MenuPrincipalView extends javax.swing.JFrame {

    private final MenuPrincipalController controller;

    /**
     * Creates new form MenuPrincipalView
     */
    public MenuPrincipalView() {
        initComponents();
        controller = new MenuPrincipalController(this);
    }
    
    // Construtor tela que eu quero ir
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuConsultar = new javax.swing.JMenu();
        jMenuItemConsultarMateria = new javax.swing.JMenuItem();
        jMenuItemConsultarNota = new javax.swing.JMenuItem();
        jMenuItemConsultarMateriaxNota = new javax.swing.JMenuItem();
        jMenuItemCadastrar = new javax.swing.JMenu();
        jMenuItemCadastrarMateria = new javax.swing.JMenuItem();
        jMenuItemCadastrarNota = new javax.swing.JMenuItem();
        jMenuItemCadastrarRelacionamentoMateriaeNota = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Notas");
        setResizable(false);

        jMenuConsultar.setText("Consultar");
        jMenuConsultar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItemConsultarMateria.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemConsultarMateria.setText("Matéria");
        jMenuItemConsultarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarMateriaActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarMateria);

        jMenuItemConsultarNota.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemConsultarNota.setText("Nota");
        jMenuConsultar.add(jMenuItemConsultarNota);

        jMenuItemConsultarMateriaxNota.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemConsultarMateriaxNota.setText("Materia x Nota");
        jMenuConsultar.add(jMenuItemConsultarMateriaxNota);

        jMenuBar1.add(jMenuConsultar);

        jMenuItemCadastrar.setText("Cadastrar");
        jMenuItemCadastrar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItemCadastrarMateria.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemCadastrarMateria.setText("Matéria");
        jMenuItemCadastrarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirCadastroMateriaActionPerformed(evt);
            }
        });
        jMenuItemCadastrar.add(jMenuItemCadastrarMateria);

        jMenuItemCadastrarNota.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemCadastrarNota.setText("Nota");
        jMenuItemCadastrar.add(jMenuItemCadastrarNota);

        jMenuItemCadastrarRelacionamentoMateriaeNota.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemCadastrarRelacionamentoMateriaeNota.setText("Relacionamento matéria e nota");
        jMenuItemCadastrar.add(jMenuItemCadastrarRelacionamentoMateriaeNota);

        jMenuBar1.add(jMenuItemCadastrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAbrirCadastroMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirCadastroMateriaActionPerformed
        controller.abrirCadastroMateria();

    }//GEN-LAST:event_jMenuItemAbrirCadastroMateriaActionPerformed

    private void jMenuItemConsultarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarMateriaActionPerformed
        controller.abrirConsultaMateria();
    }//GEN-LAST:event_jMenuItemConsultarMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenu jMenuItemCadastrar;
    private javax.swing.JMenuItem jMenuItemCadastrarMateria;
    private javax.swing.JMenuItem jMenuItemCadastrarNota;
    private javax.swing.JMenuItem jMenuItemCadastrarRelacionamentoMateriaeNota;
    private javax.swing.JMenuItem jMenuItemConsultarMateria;
    private javax.swing.JMenuItem jMenuItemConsultarMateriaxNota;
    private javax.swing.JMenuItem jMenuItemConsultarNota;
    // End of variables declaration//GEN-END:variables
}
